service: staff-scheduler
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    HTTP_ENDPOINT: 'http://13.127.2.248/schedule'

plugins:
  - '@hybridless/serverless-ecs-plugin'
  - serverless-pseudo-parameters

custom:
  aws:
    profile: personal
    accountId: 343547439778
  service: 
    port: 8080
  ecs:
    clusterName: ${self:service}-cluster
    taskDefinition:
      family: ${self:service}-task-dev
      containerDefinitions:
        - name: ${self:service}-repo
          image: ${self:custom.aws.accountId}.dkr.ecr.${self:provider.region}.amazonaws.com/${self:service}-repo:latest
          portMappings:
            - name: ${self:service}-repo-${self:custom.service.port}-tcp
              containerPort: ${self:custom.service.port}
              hostPort: ${self:custom.service.port}
              protocol: tcp
              appProtocol: http
          essential: true
          environment:
          logConfiguration:
            logDriver: awslogs
            options:
              awslogs-create-group: true
              awslogs-group: "/ecs/${self:custom.ecs.taskDefinition.family}"
              awslogs-region: "${self:provider.region}"
              awslogs-stream-prefix: "ecs"

resources:
  Resources:
    mainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: gsi_pk_1
            AttributeType: S
          - AttributeName: gsi_sk_1
            AttributeType: S
          - AttributeName: gsi_pk_2
            AttributeType: S
          - AttributeName: gsi_sk_2
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: gsi_1
            KeySchema:
              - AttributeName: gsi_pk_1
                KeyType: HASH
              - AttributeName: gsi_sk_1
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: gsi_2
            KeySchema:
              - AttributeName: gsi_pk_2
                KeyType: HASH
              - AttributeName: gsi_sk_2
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TableName: ${self:provider.stage}-schedule

    StaffSchedulerRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: StaffSchedulerRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: ecs-tasks.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: CloudWatchLogsPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "arn:aws:logs:${self:provider.region}:*:log-group:/ecs/*"
          - PolicyName: DynamoDBPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                    - dynamodb:GetItem
                  Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-schedule"
          - PolicyName: AdministratorPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: "*"
                  Resource: "*"

    StaffScheduleCluster:
      Type: AWS::ECS::Cluster
      Properties:
        ClusterName: ${self:custom.ecs.clusterName}
        CapacityProviders:
          - FARGATE
          - FARGATE_SPOT
        DefaultCapacityProviderStrategy:
          - CapacityProvider: FARGATE
            Weight: 1
          - CapacityProvider: FARGATE_SPOT
            Weight: 1

    StaffSchedulerTaskDefinition:
      Type: AWS::ECS::TaskDefinition
      Properties:
        Family: ${self:custom.ecs.taskDefinition.family}
        NetworkMode: awsvpc
        ContainerDefinitions: ${self:custom.ecs.taskDefinition.containerDefinitions}
        RequiresCompatibilities:
          - FARGATE
        Memory: "512"
        Cpu: "256"
        ExecutionRoleArn: !GetAtt StaffSchedulerRole.Arn
        RuntimePlatform:
          # Define the RuntimePlatform properties here
          cpuArchitecture: X86_64
          operatingSystemFamily: LINUX

    StaffSchedulerListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        LoadBalancerArn: !Ref StaffSchedulerElb
        Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupArn: !Ref StaffSchedulerTargetGroup

    StaffSchedulerTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        Name: ${self:service}-target-group
        Port: 80
        Protocol: HTTP
        VpcId: vpc-06906dc6ed93509c5  # Replace with the ID of your VPC
        TargetType: ip
        HealthCheckPath: /health-check

    StaffSchedulerElb:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        Name: ${self:service}-elb
        Scheme: internet-facing
        IpAddressType: ipv4
        Type: application 
        Subnets:
          - subnet-0f2f0f3511b92435f
          - subnet-03130abf6efde5935
          - subnet-0b25b3474b72782cf
        SecurityGroups:
          - sg-0976513226a6d611a
    
    StaffSchedulerService:
      Type: AWS::ECS::Service
      Properties:
        Cluster: !Ref StaffScheduleCluster
        DeploymentConfiguration:
          MaximumPercent: 200
          MinimumHealthyPercent: 100
        DesiredCount: 1
        HealthCheckGracePeriodSeconds: 0
        LoadBalancers:
          - ContainerName: ${self:service}-repo
            ContainerPort: ${self:custom.service.port}
            TargetGroupArn: !Ref StaffSchedulerTargetGroup
        TaskDefinition: !Ref StaffSchedulerTaskDefinition
        ServiceName: ${self:service}-service
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: ENABLED  # Choose "ENABLED" or "DISABLED" based on your requirements
            Subnets:
              - subnet-0f2f0f3511b92435f
              - subnet-03130abf6efde5935
              - subnet-0b25b3474b72782cf
            SecurityGroups:
              - sg-0976513226a6d611a

    MyApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:provider.stage}-${self:service}
        Body:
          paths:
            /scheduler:
              get:
                responses: {}
                x-amazon-apigateway-integration:
                  type: http_proxy
                  httpMethod: GET
                  uri: !Sub "http://${StaffSchedulerElb.DNSName}/schedule"
                security:
                  - AWS_IAM: []
              post:
                responses: {}
                x-amazon-apigateway-integration:
                  type: http_proxy
                  httpMethod: POST
                  uri: !Sub "http://${StaffSchedulerElb.DNSName}/schedule"
                security:
                  - AWS_IAM: []
              put:
                responses: {}
                x-amazon-apigateway-integration:
                  type: http_proxy
                  httpMethod: PUT
                  uri: !Sub "http://${StaffSchedulerElb.DNSName}/schedule"
                security:
                  - AWS_IAM: []
              delete:
                responses: {}
                x-amazon-apigateway-integration:
                  type: http_proxy
                  httpMethod: DELETE
                  uri: !Sub "http://${StaffSchedulerElb.DNSName}/schedule"
                security:
                  - AWS_IAM: []

    # MyApiResource:
    #   Type: AWS::ApiGateway::Resource
    #   Properties:
    #     RestApiId:
    #       Ref: MyApiGateway
    #     ParentId:
    #       Fn::GetAtt:
    #         - MyApiGateway
    #         - RootResourceId
    #     PathPart: 'scheduler'
    # MyGetMethod:
    #   Type: AWS::ApiGateway::Method
    #   Properties:
    #     RestApiId:
    #       Ref: MyApiGateway
    #     ResourceId:
    #       Ref: MyApiResource
    #     HttpMethod: 'GET'
    #     AuthorizationType: NONE
    #     Integration:
    #       Type: HTTP_PROXY
    #       IntegrationHttpMethod: GET
    #       Uri: !Sub "http://${StaffSchedulerElb.DNSName}/schedule"
    # MyPostMethod:
    #   Type: AWS::ApiGateway::Method
    #   Properties:
    #     RestApiId:
    #       Ref: MyApiGateway
    #     ResourceId:
    #       Ref: MyApiResource
    #     HttpMethod: 'POST'
    #     AuthorizationType: AWS_IAM
    #     Integration:
    #       Type: HTTP_PROXY
    #       IntegrationHttpMethod: POST
    #       Uri: !Sub "http://${StaffSchedulerElb.DNSName}/schedule"
    # MyPutMethod:
    #   Type: AWS::ApiGateway::Method
    #   Properties:
    #     RestApiId:
    #       Ref: MyApiGateway
    #     ResourceId:
    #       Ref: MyApiResource
    #     HttpMethod: 'PUT'
    #     AuthorizationType: AWS_IAM
    #     Integration:
    #       Type: HTTP_PROXY
    #       IntegrationHttpMethod: PUT
    #       Uri: !Sub "http://${StaffSchedulerElb.DNSName}/schedule"
    # MyDeleteMethod:
    #   Type: AWS::ApiGateway::Method
    #   Properties:
    #     RestApiId:
    #       Ref: MyApiGateway
    #     ResourceId:
    #       Ref: MyApiResource
    #     HttpMethod: 'DELETE'
    #     AuthorizationType: AWS_IAM
    #     Integration:
    #       Type: HTTP_PROXY
    #       IntegrationHttpMethod: DELETE
    #       Uri: !Sub "http://${StaffSchedulerElb.DNSName}/schedule"
  
    MyApiDeployment:
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId:
          Ref: MyApiGateway

    MyApiStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        StageName: ${self:provider.stage} # Replace 'dev' with the desired stage name
        RestApiId:
          Ref: MyApiGateway
        DeploymentId:
          Ref: MyApiDeployment